apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # Port that the service will expose
      targetPort: 8085 # Port on the container
      nodePort: 30001  # Port exposed on each Node (only for NodePort services)
  type: NodePort

