apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service internally
      targetPort: 8085 # Port on the container
      nodePort: 30001  # NodePort to access the service externally

